// Writes out/_redirects (Netlify) after `next build`. Posts kept their old /blog/<slug>/ URLs,
// so only the few URLs that did change need a 301.
import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';

const root = path.dirname(new URL(import.meta.url).pathname);
const contentDir = path.join(root, '../content/blog');
const outFile = path.join(root, '../out/_redirects');

const rules = [];
const add = (from, to) => {
  // Netlify may or may not normalize trailing slashes; list both forms so each is a single hop.
  const bare = from.replace(/\/$/, '');
  rules.push([bare, to], [`${bare}/`, to]);
};

// External posts never had a page on the old site; send any stray links to where they live.
for (const file of fs.readdirSync(contentDir).filter((f) => /\.mdx?$/.test(f)).sort()) {
  const { data } = matter(fs.readFileSync(path.join(contentDir, file), 'utf8'));
  if (data.url) add(`/blog/${file.replace(/\.mdx?$/, '')}`, data.url);
}

// The old sitemap URLs from @astrojs/sitemap.
rules.push(['/sitemap-index.xml', '/sitemap.xml'], ['/sitemap-0.xml', '/sitemap.xml']);

const width = Math.max(...rules.map(([from]) => from.length)) + 2;
const body = [
  '# Generated by scripts/redirects.mjs. Old Astro URLs -> new URLs.',
  ...rules.map(([from, to]) => `${from.padEnd(width)}${to}  301!`),
  '',
].join('\n');

fs.writeFileSync(outFile, body);
console.log(`Wrote ${rules.length} redirects to out/_redirects`);
