// Generated by BUCKLESCRIPT VERSION 1.10.3, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

function se(prim) {
  return prim;
}

var wrapperStyle = {
  display: "flex",
  marginTop: "32px",
  marginBottom: "32px",
  maxWidth: "512px",
  width: "100%",
  alignItems: "center",
  flexDirection: "column",
  justifyContent: "center"
};

var textStyle = {
  letterSpacing: "1.2px"
};

var harambeStyle = {
  textDecoration: "none"
};

var component = ReasonReact.statelessComponent("Footer");

function makeFooter() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  style: wrapperStyle
                }, React.createElement("small", {
                      style: textStyle
                    }, "©2017 Jake Dawkins. It\'s okay. You can ", React.createElement("a", {
                          href: "https://github.com/jakedawkins/jakedawkins.com"
                        }, "steal this."), React.createElement("a", {
                          style: harambeStyle,
                          href: "https://en.wikipedia.org/wiki/Killing_of_Harambe"
                        }, React.createElement("span", {
                              role: "img",
                              label: "monkey"
                            }, " 🐒"))));
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, makeFooter);

exports.se           = se;
exports.wrapperStyle = wrapperStyle;
exports.textStyle    = textStyle;
exports.harambeStyle = harambeStyle;
exports.component    = component;
exports.makeFooter   = makeFooter;
exports.$$default    = $$default;
exports.default      = $$default;
exports.__esModule   = true;
/* component Not a pure module */
