// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

function se(prim) {
  return prim;
}

var link = ( require('react-router-dom').Link );

var wrapperStyle = {
  display: "flex",
  marginTop: "32px",
  maxWidth: "512px",
  width: "100%",
  alignItems: "center",
  flexDirection: "column",
  justifyContent: "center"
};

var headerStyle = {
  backgroundColor: "white",
  fontWeight: "900",
  letterSpacing: "1.2px",
  padding: "8px 32px",
  textAlign: "center"
};

var subHeaderStyle = {
  backgroundColor: "white",
  fontWeight: "300",
  letterSpacing: "1.2px",
  marginBottom: "0px",
  padding: "4px 8px",
  textAlign: "center"
};

var component = ReasonReact.statelessComponent("Footer");

function makeHeader(heading, subHeading, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  style: wrapperStyle
                }, React.createElement("link", undefined, React.createElement("h1", {
                          style: headerStyle
                        }, heading)), React.createElement("h3", {
                      style: subHeaderStyle
                    }, subHeading));
    });
  return newrecord;
}

exports.se             = se;
exports.link           = link;
exports.wrapperStyle   = wrapperStyle;
exports.headerStyle    = headerStyle;
exports.subHeaderStyle = subHeaderStyle;
exports.component      = component;
exports.makeHeader     = makeHeader;
/* link Not a pure module */
